import { IUTAuctionEntity } from "./IUTAuctionEntity";
import { IUTStaticPlayerItemDataDTO } from "./IUTStaticPlayerItemDataDTO";

export interface IUTItemEntity {
  amount: number;
  authenticity: boolean;
  ballRestricted: boolean;
  bannerRestricted: boolean;
  concept: boolean;
  continuationId: string;
  contract: number;
  discardDate: number;
  discardValue: number;
  discardable: boolean;
  duplicateId: number;
  duplicateItemLoans: number;
  groups: any[];
  hasLevels: boolean;
  iconId: number;
  id: number;
  injuryGames: number;
  injuryType: string;
  lastSalePrice: number;
  leagueId: number;
  loans: number;
  loyaltyBonus: number;
  nationId: number;
  owners: number;
  pile: number;
  playStyle: number;
  preferredPosition: number;
  rareflag: number;
  rating: number;
  resourceId: number;
  stackCount: number;
  state: string;
  subtype: number;
  teamId: number;
  tifoRestricted: boolean;
  timestamp: number;
  type: string;
  untradeable: boolean;
  untradeableCount: number;
  _assetId: number;
  _attributes: number[];
  _auction: IUTAuctionEntity;
  _defensiveWorkRate: number;
  _itemPriceLimits: any;
  _lifetimeStats: number[];
  _offensiveWorkRate: number;
  _playerTraits: any;
  _preferredFoot: number;
  _skillMoves: number;
  _staticData: IUTStaticPlayerItemDataDTO;
  _stats: number[];
  _weakFoot: number;
}
